### ISSUE TITLE
429 problem

### ISSUE THREAD

**Issue by erbhosting** [0x6a69616e/kpsdk-solver#7]
hi bro
i try use it but i get 429
i change urls in part1.js with own
but i got 429
and change p,js with my script in website
but got 429
where is my problem?!

**Comment by 0x6a69616e** [comment]
Hey @erbhosting! Apologies for the inconvenience.

Could you elaborate a bit more?

Unfortunately, the current iteration is not yet capable of producing absolutely valid `x-kpsdk-*` headers. I have already been made known of this issue, and I am investigating and considering alternative approaches to resolve it.

My availability to work on this is <ins>*somewhat*</ins> limited (Eastern Time) due to schooling. So for now, I recommend you [Watch this repository](https://github.com/0x6a69616e/kpsdk-solver/watchers) for real-time updates on the active development of kpsdk-solver.
